# Generated by Django 3.2.3 on 2021-06-13 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('News_24', '0002_destination_offset'),
    ]

    operations = [
        migrations.RenameField(
            model_name='destination',
            old_name='offset',
            new_name='offer',
        ),
    ]
